# Generated by Django 4.1.5 on 2023-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
    ]
